---
- name: Install Google Chrome
  hosts: Windows
  become: yes
  tasks:
    - name: Download Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome.deb

    - name: Install Google Chrome
      apt:
        deb: /tmp/google-chrome.deb
        state: present

    - name: Remove Google Chrome .deb file
      file:
        path: /tmp/google-chrome.deb
        state: absent