---
- name: Install Python and Git on remote hosts
  hosts: Linux
  become: true
  tasks:

    - name: Install Python and Git on RedHat/CentOS
      yum:
        name:
          - python3.12
          - git
        state: present
      when: ansible_os_family == 'RedHat'
