---
- name: Test windows connectivity
  hosts: workstation
  gather_facts: false
  become: true
  become_method: ansible.builtin.runas
  become_user: vedhainfotech\svc_ansible
  tasks:
    - name: Verifiy connectivity
      ansible.windows.win_ping:
