---
- name: Install Google Chrome on Windows
  hosts: Windows
  gather_facts: false
  tasks:

    - name: Download Chrome Installer
      win_get_url:
        url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
        dest: C:\chrome_installer.exe

    - name: Install Google Chrome
      win_package:
        path: C:\chrome_installer.exe
        arguments: /silent /install
        product_id: Google Chrome
        state: present
    - name: Clean up installer
      win_file:
        path: C:\chrome_installer.exe
        state: absent 