---
- name: Check Windows connectivity
  hosts: windows
  gather_facts: false

  tasks:
    - name: Ping Windows host using WinRM
      ansible.windows.win_ping:

    - name: Display success message
      debug:
        msg: "Connection to {{ inventory_hostname }} is successful."
