---
- name: Install WinRAR on Windows
  hosts: Windows
  become: true
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install WinRAR
      win_chocolatey:
        name: winrar
        state: present
