---
- name: Test windows connectivity
  hosts: workstation
  gather_facts: false
  become: true
  become_method: ansible.builtin.runas
  become_user: vedhainfotech\svc_ansible
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install WinRAR
      win_chocolatey:
        name: winrar
        state: present
